# fly.toml app configuration file generated for kenny-chuan-movie-app on 2024-02-23T23:10:15-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kenny-chuan-movie-app'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
